name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
        package-manager-cache: false 

    - name: Setup pnpm
      uses: pnpm/action-setup@v5

    - name: Install dependencies
      run: pnpm install

    - name: Run unit tests
      run: pnpm test:once

    - name: Run lint checks
      run: pnpm lint:check

    - name: Run production build
      run: pnpm build
 
