name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install deps
      run: npm install

    - name: Run unit tests
      run: npm run test:once

    - name: Run lint checks
      run: npm run lint:check

    - name: Run production build
      run: npm run build
 
