name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  runs-on: ubuntu-latest
  test:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install deps
      run: npm install

    - name: Run unit tests
      run: npm run test